"""initial models

Revision ID: 602c6bd513aa
Revises: 
Create Date: 2026-09-22 17:24:59.629603

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '602c6bd513aa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('marketplace_order_id', sa.String(length=100), nullable=False),
    sa.Column('internal_sku', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_internal_sku'), 'order', ['internal_sku'], unique=False)
    op.create_index(op.f('ix_order_marketplace'), 'order', ['marketplace'], unique=False)
    op.create_index(op.f('ix_order_marketplace_order_id'), 'order', ['marketplace_order_id'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_table('salemetric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_date', 'marketplace', 'metric_type')
    )
    op.create_index(op.f('ix_salemetric_marketplace'), 'salemetric', ['marketplace'], unique=False)
    op.create_index(op.f('ix_salemetric_metric_date'), 'salemetric', ['metric_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salemetric_metric_date'), table_name='salemetric')
    op.drop_index(op.f('ix_salemetric_marketplace'), table_name='salemetric')
    op.drop_table('salemetric')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_marketplace_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_marketplace'), table_name='order')
    op.drop_index(op.f('ix_order_internal_sku'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
