"""initial models

Revision ID: 8e0edf439e6a
Revises: 
Create Date: 2026-09-22 17:24:56.598348

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e0edf439e6a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockupdatelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_sku', sa.String(length=50), nullable=False),
    sa.Column('previous_quantity', sa.Integer(), nullable=False),
    sa.Column('new_quantity', sa.Integer(), nullable=False),
    sa.Column('source_platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stockupdatelog_internal_sku'), 'stockupdatelog', ['internal_sku'], unique=False)
    op.create_index(op.f('ix_stockupdatelog_status'), 'stockupdatelog', ['status'], unique=False)
    op.create_table('syncevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncevent_event_type'), 'syncevent', ['event_type'], unique=False)
    op.create_index(op.f('ix_syncevent_status'), 'syncevent', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syncevent_status'), table_name='syncevent')
    op.drop_index(op.f('ix_syncevent_event_type'), table_name='syncevent')
    op.drop_table('syncevent')
    op.drop_index(op.f('ix_stockupdatelog_status'), table_name='stockupdatelog')
    op.drop_index(op.f('ix_stockupdatelog_internal_sku'), table_name='stockupdatelog')
    op.drop_table('stockupdatelog')
    # ### end Alembic commands ###
