"""initial models

Revision ID: 8e0edf439e6a
Revises: 
Create Date: 2026-09-22 17:24:56.598348

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import sqlalchemy.dialects.postgresql as pg

# revision identifiers, used by Alembic.
revision: str = '8e0edf439e6a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_audit_logs',
    sa.Column('id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('item_id', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('old_quantity', sa.Integer(), nullable=True),
    sa.Column('new_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('original_event_id', sa.String(length=255), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_audit_logs_user_id'), 'sync_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_sync_audit_logs_platform'), 'sync_audit_logs', ['platform'], unique=False)
    op.create_index(op.f('ix_sync_audit_logs_event_type'), 'sync_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_sync_audit_logs_order_id'), 'sync_audit_logs', ['order_id'], unique=False)
    op.create_index(op.f('ix_sync_audit_logs_item_id'), 'sync_audit_logs', ['item_id'], unique=False)
    op.create_index(op.f('ix_sync_audit_logs_sku'), 'sync_audit_logs', ['sku'], unique=False)
    op.create_index(op.f('ix_sync_audit_logs_created_at'), 'sync_audit_logs', ['created_at'], unique=False)
    
    op.create_table('sync_states',
    sa.Column('id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('current_quantity', sa.Integer(), nullable=False),
    sa.Column('pending_quantity', sa.Integer(), nullable=True),
    sa.Column('last_event_id', sa.String(length=255), nullable=True),
    sa.Column('last_event_type', sa.String(length=100), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_states_user_id'), 'sync_states', ['user_id'], unique=False)
    op.create_index(op.f('ix_sync_states_platform'), 'sync_states', ['platform'], unique=False)
    op.create_index(op.f('ix_sync_states_sku'), 'sync_states', ['sku'], unique=False)
    op.create_index(op.f('ix_sync_states_item_id'), 'sync_states', ['item_id'], unique=False)
    
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_idempotency_keys_event_id'), 'idempotency_keys', ['event_id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_user_id'), 'idempotency_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idempotency_keys_expires_at'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_user_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_event_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    
    op.drop_index(op.f('ix_sync_states_item_id'), table_name='sync_states')
    op.drop_index(op.f('ix_sync_states_sku'), table_name='sync_states')
    op.drop_index(op.f('ix_sync_states_platform'), table_name='sync_states')
    op.drop_index(op.f('ix_sync_states_user_id'), table_name='sync_states')
    op.drop_table('sync_states')
    
    op.drop_index(op.f('ix_sync_audit_logs_created_at'), table_name='sync_audit_logs')
    op.drop_index(op.f('ix_sync_audit_logs_sku'), table_name='sync_audit_logs')
    op.drop_index(op.f('ix_sync_audit_logs_item_id'), table_name='sync_audit_logs')
    op.drop_index(op.f('ix_sync_audit_logs_order_id'), table_name='sync_audit_logs')
    op.drop_index(op.f('ix_sync_audit_logs_event_type'), table_name='sync_audit_logs')
    op.drop_index(op.f('ix_sync_audit_logs_platform'), table_name='sync_audit_logs')
    op.drop_index(op.f('ix_sync_audit_logs_user_id'), table_name='sync_audit_logs')
    op.drop_table('sync_audit_logs')
    # ### end Alembic commands ###
