"""initial models

Revision ID: 4aa009d3aaa1
Revises: 
Create Date: 2026-09-22 17:24:58.115323

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import sqlalchemy.dialects.postgresql as pg

# revision identifiers, used by Alembic.
revision: str = '4aa009d3aaa1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_integrations',
    sa.Column('id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('external_seller_id', sa.String(length=100), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_integrations_user_id'), 'tenant_integrations', ['user_id'], unique=False)
    op.create_index(op.f('ix_tenant_integrations_platform'), 'tenant_integrations', ['platform'], unique=False)
    op.create_index(op.f('ix_tenant_integrations_external_seller_id'), 'tenant_integrations', ['external_seller_id'], unique=False)
    op.create_unique_constraint(
        'uq_tenant_integration_user_platform_seller',
        'tenant_integrations',
        ['user_id', 'platform', 'external_seller_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_integration_user_platform_seller', 'tenant_integrations', type_='unique')
    op.drop_index(op.f('ix_tenant_integrations_external_seller_id'), table_name='tenant_integrations')
    op.drop_index(op.f('ix_tenant_integrations_platform'), table_name='tenant_integrations')
    op.drop_index(op.f('ix_tenant_integrations_user_id'), table_name='tenant_integrations')
    op.drop_table('tenant_integrations')
    # ### end Alembic commands ###
