"""initial models

Revision ID: 4aa009d3aaa1
Revises: 
Create Date: 2026-09-22 17:24:58.115323

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4aa009d3aaa1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplacecredential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.Enum('mercadolivre', 'shopee', name='marketplace'), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=False),
    sa.Column('access_token', sa.String(length=2000), nullable=False),
    sa.Column('refresh_token', sa.String(length=2000), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplacecredential_marketplace'), 'marketplacecredential', ['marketplace'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplacecredential_marketplace'), table_name='marketplacecredential')
    op.drop_table('marketplacecredential')
    op.execute("DROP TYPE IF EXISTS marketplace")
    # ### end Alembic commands ###
