"""initial models

Revision ID: f2fd22e17f9c
Revises: 
Create Date: 2026-09-22 17:24:55.038744

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f2fd22e17f9c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('internal_sku', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sku_internal_sku'), 'sku', ['internal_sku'], unique=True)
    op.create_index(op.f('ix_sku_product_id'), 'sku', ['product_id'], unique=False)
    op.create_table('platformmapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('mercadolivre', 'shopee', name='platform'), nullable=False),
    sa.Column('platform_sku', sa.String(length=100), nullable=False),
    sa.Column('platform_product_id', sa.String(length=100), nullable=True),
    sa.Column('platform_variant_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platformmapping_platform'), 'platformmapping', ['platform'], unique=False)
    op.create_index(op.f('ix_platformmapping_sku_id'), 'platformmapping', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platformmapping_sku_id'), table_name='platformmapping')
    op.drop_index(op.f('ix_platformmapping_platform'), table_name='platformmapping')
    op.drop_table('platformmapping')
    op.execute("DROP TYPE IF EXISTS platform")
    op.drop_index(op.f('ix_sku_product_id'), table_name='sku')
    op.drop_index(op.f('ix_sku_internal_sku'), table_name='sku')
    op.drop_table('sku')
    op.drop_table('product')
    # ### end Alembic commands ###
